// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Livro } from '../livro';
import { Editora } from '../editora';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) { }

  async ngOnInit(): Promise<void> {
    this.editoras = this.servEditora.getEditoras();

    try {
      this.livros = await this.servLivros.obterLivros();
    } catch (error) {
      console.error('Erro ao obter livros:', error);
    }
  }

  excluir = async (codigo: string): Promise<void> => {
    try {
      await this.servLivros.excluir(codigo);
      this.livros = await this.servLivros.obterLivros();
    } catch (error) {
      console.error('Erro ao excluir livro:', error);
    }
  };

  obterNome = (codEditora: number): string => {
    return this.servEditora.getNomeEditora(codEditora);
  };
}

<main class="container mt-4">
    <h2>Catálogo de Livros</h2>


    <table class="table ">
        <thead>
            <tr class="bg-dark">
                <th class="text-light font-weight-normal">Título</th>
                <th class="text-light font-weight-normal">Resumo</th>
                <th class="text-light font-weight-normal">Editora</th>
                <th class="text-light font-weight-normal">Autores</th>

            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let livro of livros">

                <td class="d-flex flex-column">
                    {{ livro.titulo }}
                    <button class="btn btn-danger" (click)="excluir(livro.codigo)">
                        Excluir
                    </button>
                </td>
                <td>{{ livro.resumo }}</td>
                <td>{{ obterNome(livro.codEditora) }}</td>
                <td>
                    <ul>
                        <li *ngFor="let autor of livro.autores">{{ autor }}</li>
                    </ul>
                </td>

            </tr>
        </tbody>
    </table>
</main>

// clientes/livros-react/src/LivroLista.js
import React, { useState, useEffect } from 'react';
import { ControleEditora } from './controle/ControleEditora';

function LinhaLivro({ livro, excluir }) {
    const controleEditora = new ControleEditora();
    const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);

    return (
        <tr>
            <td className="d-flex flex-column">
                {livro.titulo}
                <button className="btn btn-danger" onClick={() => excluir(livro.codigo)}>Excluir</button>
            </td>
            <td>{livro.resumo}</td>

            <td>{nomeEditora}</td>
            <td>
                <ul>
                    {livro.autores.map((autor, index) => (
                        <li key={`${index}-${autor}`}>{autor}</li>
                    ))}
                </ul>
            </td>
        </tr>
    );
}


export default function LivroLista({ controleLivro }) {
    const [livros, setLivros] = useState([]);
    console.log(livros);
    const [carregado, setCarregado] = useState(false);

    useEffect(() => {
        if (!carregado) {
            controleLivro.obterLivros().then((novosLivros) => {
                setLivros(novosLivros);
                setCarregado(true);
            }).catch((erro) => {
                console.error('Erro ao obter livros:', erro);
            });
        }
    }, [carregado, controleLivro]);

    const excluir = (codigo) => {
        controleLivro.excluir(codigo)
            .then((sucesso) => {
                if (sucesso) {
                    const livrosRestantes = livros.filter((livro) => livro.codigo !== codigo);
                    setLivros(livrosRestantes);
                }
            })
            .catch((erro) => {
                console.error('Erro ao excluir livro:', erro);
            })
            .finally(() => {
                setCarregado(false);
            });
    };


    return (
        <div>
            <main class="container">
                <h1>Catálogo de Livros</h1>
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">Título</th>
                            <th scope="col">Resumo</th>
                            <th scope="col">Editora</th>
                            <th scope="col">Autores</th>

                        </tr>
                    </thead>
                    <tbody>
                        {livros.map((livro) => (
                            <LinhaLivro livro={livro} key={livro.codigo} excluir={excluir} />
                        ))}
                    </tbody>
                </table>
            </main>
        </div>
    );
}
