// clientes/livros-next/pages/LivroLista.tsx
import Head from 'next/head';
import { Menu } from '../componentes/Menu';
import { LinhaLivro } from '../componentes/LinhaLivro';
import { Livro } from '../modelo/Livro';
import styles from '../styles/page.module.css';
import { useState, useEffect } from 'react';
import { ControleLivros } from '../classes/ControleLivro';

const LivroLista: React.FC = () => {
  const controleLivros = new ControleLivros('http://localhost:3030/livros');
  const [livros, setLivros] = useState<Array<Livro>>([]);
  const [carregado, setCarregado] = useState(false);

  const obterLivros = async () => {
    try {
      const resposta = await fetch(controleLivros.baseURL);
      const dados = await resposta.json();
      setLivros(dados);
    } catch (error) {
      console.error('Erro ao obter livros:', error);
    }
  };

  const excluirLivro = async (codigo: string): Promise<boolean> => {
    try {
      const resposta = await fetch(`${controleLivros.baseURL}/${codigo}`, { method: 'DELETE' });
      return resposta.ok;
    } catch (error) {
      console.error('Erro ao excluir livro:', error);
      return false;
    }
  };


  const excluir = async (codigo: string) => {
    await controleLivros.excluir(codigo);
    setCarregado(false);
  };


  useEffect(() => {
    if (!carregado) {
      controleLivros.obterLivros().then((dados) => {
        setLivros(dados);
        setCarregado(true);
      });
    }
  }, [carregado, controleLivros]);


  return (
    <div className={styles.container}>
      <Head>
        <title>LivroLista</title>
      </Head>

      <Menu />

      <main className={styles.main}>
        <h1 className={styles.title}>Lista de Livros</h1>
        <table className="table">
          <thead>
            <tr>
              <th>Título</th>
              <th>Resumo</th>
              <th>Editora</th>
              <th>Autor</th>
            </tr>
          </thead>
          <tbody>
            {livros.map((livro, index) => (
              <LinhaLivro key={`${index}-${livro.codigo}`} livro={livro} excluir={excluir} />
            ))}

          </tbody>
        </table>
      </main>
    </div>
  );
};

export default LivroLista;

// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Livro } from '../livro';
import { Editora } from '../editora';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) { }

  async ngOnInit(): Promise<void> {
    this.editoras = this.servEditora.getEditoras();

    try {
      this.livros = await this.servLivros.obterLivros();
    } catch (error) {
      console.error('Erro ao obter livros:', error);
    }
  }

  excluir = async (codigo: string): Promise<void> => {
    try {
      await this.servLivros.excluir(codigo);
      this.livros = await this.servLivros.obterLivros();
    } catch (error) {
      console.error('Erro ao excluir livro:', error);
    }
  };

  obterNome = (codEditora: number): string => {
    return this.servEditora.getNomeEditora(codEditora);
  };
}

<main class="container mt-4">
    <h2>Catálogo de Livros</h2>


    <table class="table ">
        <thead>
            <tr class="bg-dark">
                <th class="text-light font-weight-normal">Título</th>
                <th class="text-light font-weight-normal">Resumo</th>
                <th class="text-light font-weight-normal">Editora</th>
                <th class="text-light font-weight-normal">Autores</th>

            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let livro of livros">

                <td class="d-flex flex-column">
                    {{ livro.titulo }}
                    <button class="btn btn-danger" (click)="excluir(livro.codigo)">
                        Excluir
                    </button>
                </td>
                <td>{{ livro.resumo }}</td>
                <td>{{ obterNome(livro.codEditora) }}</td>
                <td>
                    <ul>
                        <li *ngFor="let autor of livro.autores">{{ autor }}</li>
                    </ul>
                </td>

            </tr>
        </tbody>
    </table>
</main>
