// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Livro } from '../livro';
import { Editora } from '../editora';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro;
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];
  public titulo: string = '';
  public codEditora: number = 0;
  public resumo: string = '';


  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router,
    private route: ActivatedRoute
  ) {
    this.livro = new Livro('', 0, '', '', []);
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }


  incluir = (): void => {
    this.livro.setTitulo(this.titulo);
    this.livro.setResumo(this.resumo);
    this.livro.setCodEditora(this.codEditora);
    this.livro.setAutores(this.autoresForm.split('\n'));

    this.servLivros.incluir(this.livro)
      .then(() => {
        this.router.navigateByUrl('/lista');
      })
      .catch((error) => {
        console.error('Erro ao incluir livro:', error);
      });
  };
}

<main class="container mt-4">
    <h2>Dados do Livro</h2>

    <form (submit)="incluir()" ngNativeValidate>
        <div class="form-group">
            <label for="titulo">Título:</label>
            <input type="text" id="titulo" class="form-control" [(ngModel)]="titulo" name="titulo" required>
        </div>

        <div class="form-group">
            <label for="resumo">Resumo:</label>
            <textarea id="resumo" class="form-control" [(ngModel)]="resumo" name="resumo" required></textarea>
        </div>

        <div class="form-group">
            <label for="editora">Editora:</label>
            <select id="editora" class="form-control" [(ngModel)]="codEditora" name="codEditora" required>
                <option *ngFor="let editora of editoras" [value]="editora.getCodEditora()">{{ editora.getNome() }}
                </option>
            </select>
        </div>

        <div class="form-group">
            <label for="autores">Autores:</label>
            <textarea id="autores" class="form-control" [(ngModel)]="autoresForm" name="autoresForm"
                required></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Adicionar Livro</button>
    </form>
</main>

// clientes/livros-next/pages/LivroDados.tsx
import Head from 'next/head';
import { Menu } from '../componentes/Menu';
import { ControleEditora } from '../classes/ControleEditora';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import styles from '../styles/page.module.css';
import { Livro } from '../modelo/Livro';

const controleEditora = new ControleEditora();
const baseURL = "http://localhost:3000/api/livros";

const LivroDados: React.FC = () => {
  const [opcoes, setOpcoes] = useState<Array<{ value: number; text: string }>>([]);
  const [titulo, setTitulo] = useState<string>('');
  const [resumo, setResumo] = useState<string>('');
  const [autores, setAutores] = useState<string>('');
  const [codEditora, setCodEditora] = useState<number>(0);
  const router = useRouter();

  useEffect(() => {
    const editoras = controleEditora.getEditoras();
    const opcoesEditoras = editoras.map((editora) => ({
      value: editora.getCodEditora(),
      text: editora.getNome(),
    }));
    setOpcoes(opcoesEditoras);
  }, []);

  const incluirLivro = async (livro: Livro) => {
    try {
      const resposta = await fetch(baseURL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(livro),
      });
      return resposta.ok;
    } catch (error) {
      console.error('Erro ao incluir livro:', error);
      return false;
    }
  };

  const tratarCombo = (event: React.ChangeEvent<HTMLSelectElement>) => {
    setCodEditora(Number(event.target.value));
  };

  const incluir = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    const novoLivro = new Livro('', 0, "", "", [""]);
    novoLivro.setCodigo('');
    novoLivro.setCodEditora(codEditora);
    novoLivro.setTitulo(titulo);
    novoLivro.setResumo(resumo);
    novoLivro.setAutores(autores.split('\n').map((autor) => autor.trim()));


    const sucesso = await incluirLivro(novoLivro);
    if (sucesso) {
      router.push('/LivroLista');
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>LivroDados</title>
      </Head>

      <Menu />

      <main className={styles.main}>
        <h1 className={styles.title}>Incluir Livro</h1>
        <form onSubmit={incluir} className='w-100'>
          <div className="mb-3">
            <label htmlFor="titulo" className="form-label text-dark">
              Título
            </label>
            <input
              type="text"
              className="form-control"
              id="titulo"
              value={titulo}
              onChange={(e) => setTitulo(e.target.value)}
            />
          </div>
          <div className="mb-3">
            <label htmlFor="resumo" className="form-label text-dark">
              Resumo
            </label>
            <textarea
              className="form-control"
              id="resumo"
              value={resumo}
              onChange={(e) => setResumo(e.target.value)}
            ></textarea>
          </div>
          <div className="mb-3">
            <label htmlFor="autores" className="form-label text-dark">
              Autores (um por linha)
            </label>
            <textarea
              className="form-control"
              id="autores"
              value={autores}
              onChange={(e) => setAutores(e.target.value)}
            ></textarea>
          </div>
          <div className="mb-3">
            <label htmlFor="codEditora" className="form-label text-dark">
              Editora
            </label>
            <select
              className="form-select"
              id="codEditora"
              value={codEditora}
              onChange={tratarCombo}
            >
              {opcoes.map((opcao) => (
                <option key={opcao.value} value={opcao.value}>
                  {opcao.text}
                </option>
              ))}
            </select>
          </div>
          <button type="submit" className="btn btn-primary">
            Incluir
          </button>
        </form>
      </main>
    </div>
  );
};

export default LivroDados;
