// clientes/livros-react/src/LivroDados.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Livro } from './modelo/Livro'

export default function LivroDados({ controleLivro, controleEditora }) {

    const opcoes = controleEditora.getEditoras().map((editora) => ({
        value: editora.codEditora,
        text: editora.nome,
    }));

    const [titulo, setTitulo] = useState('');
    const [resumo, setResumo] = useState('');
    const [autores, setAutores] = useState('');
    const [codEditora, setCodEditora] = useState(opcoes[0].value);
    const navigate = useNavigate();

    const tratarCombo = (event) => {
        setCodEditora(Number(event.target.value));
    };

    const incluir = (event) => {
        event.preventDefault();

        const autoresArray = autores.split('\n').map((autor) => autor.trim());

        const novoLivro = new Livro('', codEditora, titulo, resumo, autoresArray);

        controleLivro.incluir(novoLivro)
            .then((sucesso) => {
                if (sucesso) {

                    navigate('/');
                } else {
                    console.error('Erro ao incluir o livro.');
                }
            })
            .catch((erro) => {
                console.error('Erro ao incluir o livro:', erro);
            });
    };


    return (
        <main className='container'>
            <h1>Dados do Livro</h1>
            <form onSubmit={incluir}>
                <div className="form-group d-flex flex-column">
                    <label htmlFor="titulo">Título</label>
                    <input class="form-control"
                        type="text"
                        id="titulo"
                        value={titulo}
                        onChange={(event) => setTitulo(event.target.value)}
                    />
                </div>
                <div className="form-group  d-flex flex-column">
                    <label htmlFor="resumo">Resumo</label>
                    <textarea class="form-control"
                        id="resumo"
                        value={resumo}
                        onChange={(event) => setResumo(event.target.value)}
                    />
                </div>
                <div className="form-group  d-flex flex-column">
                    <label htmlFor="editora">Editora</label>
                    <select class="form-control" id="editora" value={codEditora} onChange={tratarCombo}>
                        {opcoes.map((opcao) => (
                            <option key={opcao.value} value={opcao.value}>
                                {opcao.text}
                            </option>
                        ))}
                    </select>
                </div>
                <div className="form-group  d-flex flex-column">
                    <label htmlFor="autores">Autores (1 por linha)</label>
                    <textarea class="form-control"
                        id="autores"
                        value={autores}
                        onChange={(event) => setAutores(event.target.value)}
                    />
                </div>

                <button type="submit" className="btn btn-primary">
                    Salvar dados
                </button>
            </form>
        </main>
    );
}

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Livro } from '../livro';
import { Editora } from '../editora';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro;
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];
  public titulo: string = '';
  public codEditora: number = 0;
  public resumo: string = '';


  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router,
    private route: ActivatedRoute
  ) {
    this.livro = new Livro('', 0, '', '', []);
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }


  incluir = (): void => {
    this.livro.setTitulo(this.titulo);
    this.livro.setResumo(this.resumo);
    this.livro.setCodEditora(this.codEditora);
    this.livro.setAutores(this.autoresForm.split('\n'));

    this.servLivros.incluir(this.livro)
      .then(() => {
        this.router.navigateByUrl('/lista');
      })
      .catch((error) => {
        console.error('Erro ao incluir livro:', error);
      });
  };
}

<main class="container mt-4">
    <h2>Dados do Livro</h2>

    <form (submit)="incluir()" ngNativeValidate>
        <div class="form-group">
            <label for="titulo">Título:</label>
            <input type="text" id="titulo" class="form-control" [(ngModel)]="titulo" name="titulo" required>
        </div>

        <div class="form-group">
            <label for="resumo">Resumo:</label>
            <textarea id="resumo" class="form-control" [(ngModel)]="resumo" name="resumo" required></textarea>
        </div>

        <div class="form-group">
            <label for="editora">Editora:</label>
            <select id="editora" class="form-control" [(ngModel)]="codEditora" name="codEditora" required>
                <option *ngFor="let editora of editoras" [value]="editora.getCodEditora()">{{ editora.getNome() }}
                </option>
            </select>
        </div>

        <div class="form-group">
            <label for="autores">Autores:</label>
            <textarea id="autores" class="form-control" [(ngModel)]="autoresForm" name="autoresForm"
                required></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Adicionar Livro</button>
    </form>
</main>
